### PR TITLE
webfaf: Unbundle patternfly and other assets

### PR DESCRIPTION
**Pull request by mkutlak**
Unbundle [Patternfly](https://github.com/patternfly/patternfly) and put custom css modifications for FAF to separate file.
Part of the PR are fixes for bugs that somehow broke the style of the web.

Other unbundled assets:
- jQuery
- DataTables
- moment.js
- typeahead.js

Container:
`docker pull mkutlak/faf-unbundle`

### CODE REVIEW

**Comment by marusak** [comment]
> Some of the packages are not available for EL7 yet.

What does mean `yet`?

**Comment by marusak** [comment]
Tables are overflowing. Note that in the current code when zooming too much, tables do not fit the page. In this code, tables always fit the page (which I like more, to be honest), but I think it is unacceptable that some fields may overflow (can be found on more places).
b1-overflow
overflow

**Comment by mkutlak** [comment]
> Tables are overflowing.

This should be fixed with the last commit.


> Note that in the current code when zooming too much, tables do not fit the page. In this code, tables always fit the page

The last commit sort of goes back to the current behaviour - if the page width is less than ~650px (width of reports/problems table header) then the tables won't fit the page.

**Comment by mkutlak** [comment]
All the required packages should now be available for EL (from Copr repo) and Fedora. 

And I've corrected colors for menu in navigation bar.

**Pull request merged**
