### PR TITLE
Webfaf2 improve filters

### PR DESCRIPTION
**Pull request by mbrysa**

### CODE REVIEW

**Comment by sorki** [comment]
Newly added stuff is missing in makefile & spec

**Comment by mbrysa** [comment]
I amended the two Makefiles. Changes to spec are not necessary, as we use `*.css` and `*.js`.

**Comment by sorki** [comment]
What's the reason behind changing Component multiselect? For me I doesn't look like an improvement - actually quite the opposite as it looks inconsistent compared to surrounding fields, there's no way to go through a list of components, I allows arbitrary values and usage is rather cumbersome compared to previous version.

**Comment by mbrysa** [comment]
1. It takes about 5 seconds to open the dropdown with current Fedora components on not-so-old PCs.
2. This way people can paste in a comma-separated text list of components that they already have in their BZ query.

I'm of course open to suggestions on how to do in a more UX consistent way.

**Pull request merged**
