### PR TITLE
webfaf: Fix serialization of reports with solutions

### PR DESCRIPTION
**Pull request by ernestask**
Currently, a dictionary is being passed to jsonify() from Flask that
includes an array of Solution objects (if any exist). The result is a
TypeError, because Python classes are not JSON-serializable, hence the
need to take \_\_dict\_\_ first. Moreover, the “since” attribute of type
datetime.datetime needs to be stringified, because it’s also not
JSON-serializable.

### CODE REVIEW

**Comment by ernestask** [comment]
Or maybe I should rather extend the class to allow serialization, because the exact same problem occurs elsewhere.

**Comment by ernestask** [comment]
retest this please

**Comment by ernestask** [comment]
test this please

**Comment by mgrabovsky** [comment]
Pylint seems to take issue with this:
```
************* Module pyfaf.utils.json
pyfaf/utils/json.py:23:4: W0221: Parameters differ from overridden 'default' method (arguments-differ)
pyfaf/utils/json.py:23:4: E0202: An attribute defined in json.encoder line 158 hides this method (method-hidden)
```

**Comment by ernestask** [comment]
Those aren’t supposed to happen with the latest version of pylint, hence me scrambling to ditch Jenkins.

**Comment by ernestask** [comment]
But I see that even with 2.4.4 it happens.

**Comment by ernestask** [comment]
https://github.com/PyCQA/pylint/issues/414

**Comment by mgrabovsky** [comment]
Looks good to me otherwise.

**Comment by ernestask** [comment]
Argh, too fast. I was adding a comment to make pylint ignore the method. Will just push directly. :smiling_imp:

**Comment by ernestask** [comment]
https://github.com/abrt/faf/commit/37cd65da01eb4703d64f27498ce562759b0ce6ba
https://github.com/abrt/faf/commit/5f70f6d0b7e21b740cbd4aa8ee2c50bcc8def988

**Comment by mgrabovsky** [comment]
Oi, one more thing:
```
RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/lib/python3.7/site-packages/pyfaf/utils/__pycache__/json.cpython-37.opt-1.pyc
   /usr/lib/python3.7/site-packages/pyfaf/utils/__pycache__/json.cpython-37.pyc
```
Indeed too hasty :{

**Comment by ernestask** [comment]
Shcrap. Every time.

**Comment by ernestask** [comment]
https://github.com/abrt/faf/commit/5e15cfc50f363567e5f638655d5ee14fbe6bcc0a

**Comment by ernestask** [comment]
Gah, this introduces a circular import that breaks things. Moreover, there already exists a `WebfafJSONEncoder` class that I could (ab)use. Going to create a PR with a revert, updated version and a test.

**Pull request merged**
