### PR TITLE
"duplicate of" mantis bug relationships can be empty

### PR DESCRIPTION
**Pull request by djuarezg**
Not sure how to fully test this as building the container image still generates an image without these changes.

I am trying to build it with `podman build -f container/Dockerfile ./`

EDIT: 
```
cd faf/container
make build
```
My bad

### CODE REVIEW

**Comment by ernestask** [comment]
Is there an example of this in the wild to inspect?

**Comment by djuarezg** [comment]
https://bugs.centos.org/view.php?id=11115 causes:

```
[2020-05-25 14:01:20] INFO:faf.AttachCentosBugs: Processing Mantis issue #11115
[2020-05-25 14:01:20] DEBUG:zeep.transports: HTTP Post to https://bugs.centos.org/api/soap/mantisconnect.php:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:mc_issue_get xmlns:ns0="http://futureware.biz/mantisconnect"><username>testdjg</username><password>abrtanalytics</password><issue_id>11115</issue_id></ns0:mc_issue_get></soap-env:Body></soap-env:Envelope>
[2020-05-25 14:01:20] DEBUG:urllib3.connectionpool: Resetting dropped connection: bugs.centos.org
[2020-05-25 14:01:21] DEBUG:urllib3.connectionpool: https://bugs.centos.org:443 "POST /api/soap/mantisconnect.php HTTP/1.1" 200 4612
[2020-05-25 14:01:21] DEBUG:zeep.transports: HTTP Response from https://bugs.centos.org/api/soap/mantisconnect.php (status: 200):
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://futureware.biz/mantisconnect" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:mc_issue_getResponse><return xsi:type="ns1:IssueData"><id xsi:type="xsd:integer">11115</id><view_state xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">public</name></view_state><last_updated xsi:type="xsd:dateTime">2016-06-29T11:31:22+00:00</last_updated><project xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">23</id><name xsi:type="xsd:string">CentOS-7</name></project><category xsi:type="xsd:string">gnome-packagekit</category><priority xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">50</id><name xsi:type="xsd:string">urgent</name></priority><severity xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">70</id><name xsi:type="xsd:string">crash</name></severity><status xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">90</id><name xsi:type="xsd:string">closed</name></status><reporter xsi:type="ns1:AccountData"><id xsi:type="xsd:integer">24461</id><name xsi:type="xsd:string">Hayo</name></reporter><summary xsi:type="xsd:string">Please start working on 0009917: [abrt] gnome-packagekit-installer: gpk_application_get_det....</summary><reproducibility xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">always</name></reproducibility><date_submitted xsi:type="xsd:dateTime">2016-06-29T11:29:21+00:00</date_submitted><sponsorship_total xsi:type="xsd:integer">0</sponsorship_total><resolution xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">60</id><name xsi:type="xsd:string">duplicate</name></resolution><description xsi:type="xsd:string">Nobody works on issue 0009917 since six months, just because its Severity is set to 'minor'. Completely disregarding the fact that roundabout 50 people have reported the similar problem meanwhile. &#13;
&#13;
Please close this defect as a duplicate and start investigating on issue &#13;
"0009917: [abrt] gnome-packagekit-installer: gpk_application_get_details_cb(): gpk-application killed by SIGSEGV".&#13;
&#13;
Personal remark: It is a bad habit on any software project, and in particular this one, to ignore issues with low priority without even looking at them. This assumes that the initial reporter has the competency to set the correct severity and priority. Which clearly is a false expectation.&#13;
&#13;
My product version is:&#13;
&#13;
[osboxes@osboxes ~]$ cat /etc/issue&#13;
\S&#13;
Kernel \r on an \m&#13;
&#13;
So I can only tell it is CentOS 7.</description><steps_to_reproduce xsi:type="xsd:string">(Install and) start 'System Tools' -&gt; 'Software' or /usr/bin/gpk-application and search for "docker".&#13;
Crash.</steps_to_reproduce><attachments SOAP-ENC:arrayType="ns1:AttachmentData[0]" xsi:type="SOAP-ENC:Array"/><notes SOAP-ENC:arrayType="ns1:IssueNoteData[1]" xsi:type="SOAP-ENC:Array"><item xsi:type="ns1:IssueNoteData"><id xsi:type="xsd:integer">26995</id><reporter xsi:type="ns1:AccountData"><id xsi:type="xsd:integer">1999</id></reporter><text xsi:type="xsd:string">duplicate of 9917</text><view_state xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">public</name></view_state><date_submitted xsi:type="xsd:dateTime">2016-06-29T11:31:16+00:00</date_submitted><last_modified xsi:type="xsd:dateTime">2016-06-29T11:31:16+00:00</last_modified><time_tracking xsi:type="xsd:integer">0</time_tracking><note_type xsi:type="xsd:integer">0</note_type><note_attr xsi:type="xsd:string"></note_attr></item></notes><custom_fields SOAP-ENC:arrayType="ns1:CustomFieldValueForIssueData[2]" xsi:type="SOAP-ENC:Array"><item xsi:type="ns1:CustomFieldValueForIssueData"><field xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">1</id><name xsi:type="xsd:string">abrt_hash</name></field><value xsi:type="xsd:string"></value></item><item xsi:type="ns1:CustomFieldValueForIssueData"><field xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">2</id><name xsi:type="xsd:string">URL</name></field><value xsi:type="xsd:string"></value></item></custom_fields><monitors SOAP-ENC:arrayType="ns1:AccountData[0]" xsi:type="SOAP-ENC:Array"/><sticky xsi:type="xsd:boolean">false</sticky><tags SOAP-ENC:arrayType="ns1:ObjectRef[0]" xsi:type="SOAP-ENC:Array"/></return></ns1:mc_issue_getResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

[2020-05-25 14:01:21] CRITICAL:faf: Action failed unexpectedly: TypeError: 'NoneType' object is not iterable
```

I cannot provide the stacktrace but basically it referred to that specific line of code.

**Comment by djuarezg** [comment]
Am I missing something? Building the image and inspecting `/usr/lib/python3.8/site-packages/pyfaf/bugtrackers/mantisbt.py` does not show my changes

**Comment by ernestask** [comment]
Did you commit your changes? Tito does not deal with dirty trees.

**Comment by ernestask** [comment]
That’s definitely something that should be addressed in the documentation. I can also trigger a Copr build in Packit, so you would be able to just install it to an existing container.

**Comment by ernestask** [comment]
Looks good to me, but can you fix the commit message? Use something like

    mantisbt: Handle duplicates with no relationships

    Currently, X happens, because Y, which can be observed in <link to that bug>.
    This commit fixes Y to do Z.

And keep it 50/72 columns for subject and body, respectively.

**Pull request merged**
