### PR TITLE
mantisbt: Use zeep instead of suds

### PR DESCRIPTION
**Pull request by marusak**
Signed-off-by: Matej Marusak <mmarusak@redhat.com>

### CODE REVIEW

**Comment by marusak** [comment]
Failed test: `No matching package to install: 'python3-zeep'`. Its here: https://copr.fedorainfracloud.org/coprs/g/abrt/faf-el7/

**Comment by marusak** [comment]
Implements #672

**Comment by mkutlak** [comment]
`python3-zeep` should now be available for the build.

@trapas retest this please

**Comment by mkutlak** [comment]
You should add a note to wiki/README that you need to either add a copr repo or install `zeep` with pip to build FAF.

**Comment by marusak** [comment]
@mkutlak - will do, when it gets merged.

**Pull request merged**
