### PR TITLE
Fix RHEL 8 builds

### PR DESCRIPTION
**Pull request by michalfabik**
See commits.

Signed-off-by: Michal Fabik <mfabik@redhat.com>

### CODE REVIEW

**Comment by mzidek-gh** [comment]
Hi, Patch looks good to me. It compiles on f32 and newer.

ACK.

**Review by mzidek-gh — APPROVED** [review]

**Comment by michalfabik** [comment]
I'll probably add some more stuff here. There's a couple more issues.

**Comment by michalfabik** [comment]
Also, this seems to fix the broken `make build_local` in `faf/container`.

**Comment by mzidek-gh** [comment]
Thanks. ACK. Merging in 10, 9, 8 ...

**Pull request merged**
