### PR TITLE
HACKING: Mention docker in building section

### PR DESCRIPTION
**Pull request by marusak**
Signed-off-by: Matej Marusak <mmarusak@redhat.com>

### CODE REVIEW

**Comment by mkutlak** [comment]
I would add a bit of formatting to it.

```markdown
Prerequisite:
Docker, see for example [this guide](https://developer.fedoraproject.org/tools/docker/docker-installation.html)
```
Prerequisite:
Docker, see for example [this guide](https://developer.fedoraproject.org/tools/docker/docker-installation.html)

🢃 to 🢃 
 
``` markdown
Prerequisite:
- Docker - see for example [this guide](https://developer.fedoraproject.org/tools/docker/docker-installation.html)
```

Prerequisite:
- Docker - see for example [this guide](https://developer.fedoraproject.org/tools/docker/docker-installation.html)

**Comment by mkutlak** [comment]
@trapas test this please

**Comment by mkutlak** [comment]
@trapas test this please

**Comment by marusak** [comment]
@mkutlak updated

**Pull request merged**
