### PR TITLE
do not disable maintainer mode (by default)

### PR DESCRIPTION
**Pull request by praiskup**
(commit message has the documentation)

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by praiskup** [comment]
Hehe, funny name for bot, btw.  Czech contributors might feel a bit sad that their
contribution is bothersome.

**Comment by marusak** [comment]
ok to test

**Comment by marusak** [comment]
test this please

**Comment by marusak** [comment]
Thank you for the patch :)

> Hehe, funny name for bot, btw. Czech contributors might feel a bit sad that their
> contribution is bothersome.

Yeah, I was surprised as well when this bot commented on my PR for the first time

**Comment by xsuchy** [comment]
Reading the documentation - isn't the better thing to completely remove the `AM_MAINTAINER_MODE` line?
https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html

**Comment by praiskup** [comment]
@xsuchy, probably yes, I do not want to be over-intrusive here.

The effect of `AM_MAINTAINER_MODE([enable])` is **only** that users still have the `./configure --disable-maintainer-mode` tool in hand.  Considering that there probably were reasons to add the `AM_MAINTAINER_MODE` historically, it could be a good compromise.

**Comment by praiskup** [comment]
Should I drop `AM_MAINTAINER_MODE` entirely, then?

**Comment by xsuchy** [comment]
Git-blame says that the line is there since initial commit in 2011. I'd say: wipe it away.

**Comment by praiskup** [comment]
Ok, updated.

**Pull request merged**
