### PR TITLE
pylint: allow 120 chars on line

### PR DESCRIPTION
**Pull request by xsuchy**
80 is soo oldies. most terms nowdays are capable to show 120 chars.

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by marusak** [comment]
Agree.
However we should work on this a lot more - firstly make the code pep8 compliant (a lot of easy and small fixes) https://github.com/abrt/faf/issues/157 and even better always check if the code is still pep8 compliant https://github.com/abrt/faf/issues/158

**Comment by xsuchy** [comment]
> make the code pep8 compliant

I have two high shool interns. Who are working on that right now. You can expect PR next day.

**Comment by jfilak** [comment]
Well, 80 characters allows you to vertically split your monitor and have two terminals on one screen. I use this setup often.

**Pull request merged**
