### PR TITLE
Fix two bugs in handling of RPM headers

### LINKED ISSUE #943: value too long
I got on retrace.f.o:

```
[2020-09-22 21:47:09] CRITICAL:faf: Action failed unexpectedly: DataError: (psycopg2.DataError) value too long for type character varying(1024)

[SQL: INSERT INTO packagedependencies (package_id, type, name, flags, epoch, version, release) VALUES (%(package_id)s, %(type)s, %(name)s, %(flags)s, %(epoch)s, %(version)s, %(release)s) RETURNING packagedependencies.id]
[parameters: {'package_id': 324375, 'type': 'PROVIDES', 'name': 'kmod(msr.ko)kmod(cpuid.ko)kmod(glue_helper.ko)kmod(aesni-intel.ko)kmod(iosf_mbi.ko)kmod(watch_queue.ko)kmod(zswap.ko)kmod(zpool.ko)kmod(zbud.ko)kmod( ... (5027 characters truncated) ... es.ko)kmod(xt_tcpudp.ko)kmod(tcp_cubic.ko)kmod(xfrm_algo.ko)kmod(xfrm_user.ko)kmod(unix.ko)kmod(ipv6.ko)kmod(mip6.ko)kmod(af_packet.ko)kmod(fbdev.ko)', 'flags': 32768, 'epoch': None, 'version': None, 'release': None}]
(Background on this error at: http://sqlalche.me/e/9h9h)
```

With faf-2.2.0-1.el8.noarch

### LINKED ISSUE #958: reposync fails to sync packages to db
For info: I've updated my Dockerfile to use Fedora 33. There are no other changes.

## How to reproduce:
1) Download packages:
```
$ sudo dnf --releasever=33 --enablerepo=\*debuginfo\* -y --installroot=/tmp/fedora33  install --downloadonly --destdir /tmp/fedora33/ abrt-addon-ccpp shadow-utils  gdb rpm will-crash firefox
```
2) Add repository with downloaded packages:
``` bash
$ faf repoadd f33 dnf file:///tmp/fedora33
```
3) Assign repo to release
``` bash
$ faf repoassign f33 "Fedora 33" x86_64
```
4) Run reposync
``` bash
$ faf reposync
```

5) Crash
``` bash
[2020-10-29 19:45:40] INFO:faf.RepoSync: Processing repo 'f33' assigned with OpSysRelease                                                                                                                                                     
[2020-10-29 19:45:40] DEBUG:dnf: User-Agent: constructed: 'libdnf (Fedora 33; container; Linux.x86_64)'                                                                                                                                       
[2020-10-29 19:45:40] INFO:dnf: Added faf_f33-0 repo from file:///tmp/fedora33                                                                                                                                                                
[2020-10-29 19:45:40] INFO:faf.RepoSync: Processing repository 'f33' assigned to OS release '33' and arch 'x86_64', URL: '(['file:///tmp/fedora33'],)'                                                                                        
[2020-10-29 19:45:40] DEBUG:dnf: repo: using cache for: faf_f33-0                                                                                                                                                                             
[2020-10-29 19:45:40] DEBUG:dnf: faf_f33-0: using metadata from Thu Oct 29 19:39:02 2020.                                                                                                                                                     
[2020-10-29 19:45:40] INFO:dnf: Last metadata expiration check: 0:03:44 ago on Thu Oct 29 19:41:56 2020.                                                                                                                                      
[2020-10-29 19:45:40] DEBUG:dnf: User-Agent: constructed: 'libdnf (Fedora 33; container; Linux.x86_64)'                                                                                                                                       
[2020-10-29 19:45:40] INFO:faf.RepoSync: Repository has '641' packages                                                                                                                                                                        
[2020-10-29 19:45:40] INFO:faf.RepoSync: [1 / 641] Processing package abattis-cantarell-fonts                                                                                                                                                 
[2020-10-29 19:45:40] DEBUG:faf.RepoSync: Known package abattis-cantarell-fonts-0.201-4.fc33.noarch.rpm                                                                                                                                       
[2020-10-29 19:45:40] INFO:faf.RepoSync: [2 / 641] Processing package abrt                                                                                                                                                                    
[2020-10-29 19:45:40] DEBUG:faf.RepoSync: Known package abrt-2.14.4-7.fc33.x86_64.rpm                                                                                                                                                         
[2020-10-29 19:45:40] INFO:faf.RepoSync: [3 / 641] Processing package abrt-addon-ccpp                                                                                                                                                         
[2020-10-29 19:45:40] DEBUG:faf.RepoSync: Adding build abrt-addon-ccpp-2.14.4                                                                                                                                                                 
[2020-10-29 19:45:40] INFO:faf.RepoSync: Adding link between build abrt-addon-ccpp-2.14.4 operating system 'Fedora', release '33 and architecture x86_64                                                                                      
[2020-10-29 19:45:40] INFO:faf.RepoSync: Adding package abrt-addon-ccpp-2.14.4-7.fc33.x86_64.rpm                                                                                                                                              
[2020-10-29 19:45:40] INFO:faf.RepoSync: Downloading file:///tmp/fedora33/abrt-addon-ccpp-2.14.4-7.fc33.x86_64.rpm                                                                                                                            
[2020-10-29 19:45:40] DEBUG:faf.pyfaf.faf_rpm: abrt-addon-ccpp-2.14.4-7.fc33.x86_64 contains 61 files                                                                                                                                         
[2020-10-29 19:45:40] CRITICAL:faf: Action failed unexpectedly: InvalidRequestError: Can't start a SAVEPOINT transaction when no existing transaction is in progress                                                                          
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/usr/bin/faf", line 152, in <module>                                                                                                                                                                                                  
    main()                                                                                                                                                                                                                                    
  File "/usr/bin/faf", line 132, in main                                                                                                                                                                                                      
    exitcode = cmdline.func(cmdline, db)                                                                               
  File "/usr/lib/python3.9/site-packages/pyfaf/actions/reposync.py", line 246, in run                                  
    store_rpm_deps(db, package, repo_instance['nogpgcheck'])                                                           
  File "/usr/lib/python3.9/site-packages/pyfaf/faf_rpm.py", line 90, in store_rpm_deps                                 
    db.session.begin_nested()                                                                                          
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 986, in begin_nested                       
    return self.begin(nested=True)                                                                                     
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 960, in begin                              
    self.transaction = SessionTransaction(self, nested=nested)                                                         
  File "/usr/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 228, in __init__                           
    raise sa_exc.InvalidRequestError(                                                                                  
sqlalchemy.exc.InvalidRequestError: Can't start a SAVEPOINT transaction when no existing transaction is in progress
```

possible suspect PR:
https://github.com/abrt/faf/pull/930


```bash
$ faf --version
ABRT Analytics v2.3.0
```

### PR DESCRIPTION
**Pull request by mgrabovsky**
These changes fix a few bugs in `faf_rpm` which made reposync unusable a while ago:

* Skip _Provides_ longer than 1024 characters when storing dependencies from RPM headers.
* Skip misformatted _Provides_ instead of trying to roll back the whole transaction.
* Moreover, only store _Provides_ items in the database since we never use either of the other two (_Requires_ or _Conflicts_).

We should migrate away from `autocommit` eventually, though it's not yet clear to me what the practical implications are.

See commits for details.

Fixes #943
Fixes #958

### CODE REVIEW

**Comment by mgrabovsky** [comment]
This is going to need a bit more polishing in the related tests.

**Comment by mgrabovsky** [comment]
Ready for review now.

**Comment by msrb** [comment]
Ouch... these types of bugs are the worst. Thanks for looking into it @mgrabovsky :wink: 

Review in progress now...

**Review by msrb — APPROVED** [review]

**Comment by msrb** [comment]
Looks good to me, but my knowledge of the code base is very very limited.

**Review by michalfabik — APPROVED** [review]

**Comment by michalfabik** [comment]
Looks good to me, LGTM.

**Pull request merged**
