### PR TITLE
tests: Retry rpm_metadata_tests

### PR DESCRIPTION
**Pull request by marusak**
DO NOT MERGE, THIS is still an experiment, pt. 2

Signed-off-by: Matej Marusak <mmarusak@redhat.com>

### CODE REVIEW

**Comment by marusak** [comment]
pt.1 3/18 failed

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
retest this please

**Comment by xsuchy** [comment]
Closing, please reopen if you will need this again.

**Pull request closed without merging**
