### PR TITLE
Fix codespell issues

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @marusak,

I fixed some [codespell](https://github.com/codespell-project/codespell) issues. See,

```
$ codespell --skip="./src/webfaf/static/*,./.git*,*llvm.py,*sample-1.0-1.fc18.noarch.rpm"
```

You could be checking this in a CI, like CircleCI, [see](https://github.com/grafana/grafana/blob/master/.circleci/config.yml). Thanks!

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by xsuchy** [comment]
retest this please

**Comment by xsuchy** [comment]
test this please

**Comment by mkutlak** [comment]
LGTM. Thank you @mjtrangoni

**Pull request merged**
