### PR TITLE
Improve performance of SQL

### PR DESCRIPTION
**Pull request by marusak**

### CODE REVIEW

**Comment by xsuchy** [comment]
Can you please rebase?

**Comment by marusak** [comment]
@xsuchy rebased

**Comment by marusak** [comment]
retest this please

**Comment by marusak** [comment]
This is the query, that is produced as default after this PR

```
WITH base AS (                                                                  
    SELECT problems.id as id, reports.id as report_id, reporthistorydaily.count as count,
       reports.type as report_type, reportbacktraces.crashfn as crashfn,        
       reportbacktraces.id as rb_id                                             
       FROM problems                                                            
       JOIN reports ON problems.id = reports.problem_id                         
       JOIN reporthistorydaily ON reports.id = reporthistorydaily.report_id     
       JOIN reportbacktraces ON reports.id = reportbacktraces.report_id         
       WHERE reporthistorydaily.day >= '2018-8-1' AND reporthistorydaily.day <= '2018-8-15'
           AND (reports.max_certainty < 100 OR reports.max_certainty IS NULL)   
       ),                                                                       
    base_count AS (                                                             
    SELECT base.id AS id, base.crashfn, COUNT(*) AS func_count                  
       FROM base                                                                
       GROUP BY base.id, base.crashfn                                           
    )                                                                           
                                                                                
SELECT base.id AS id,                                                           
       STRING_AGG(DISTINCT(opsyscomponents.name), ', ') AS components,          
       MAX(comp.comp_count) AS comp_count,                                      
       MAX(base.count) AS count,                                                
       MAX(base_count.crashfn) AS crashfn,                                      
       COUNT(DISTINCT(reportmantis.mantisbug_id)) AS mantisbugs_count,          
       COUNT(DISTINCT(reportbz.bzbug_id)) AS bzbugs_count,                      
       MAX(mantisbugs.status) AS mantis_status,                                 
       MAX(bzbugs.status) AS bz_status,                                         
       MAX(fix.pkg_name) AS pkg_name,                                           
       MAX(fix.pkg_version) AS pkg_version,                                     
       MAX(fix.pkg_release) AS pkg_release,                                     
       MAX(fix.name) AS opsys,                                                  
       MIN(fix.version) AS opsys_release,                                       
       MAX(tainted.count) AS tainted_count                                      
                                                                                
FROM base                                                                       
JOIN base_count ON base_count.id = base.id                                      
JOIN (SELECT base.id AS id, SUM(base.count) AS count                            
      FROM base                                                                 
      GROUP BY base.id) AS total_count                                          
ON total_count.id = base.id                                                     
JOIN (SELECT base_count.id, MAX(base_count.func_count) AS max_count             
      FROM base_count                                                           
      GROUP BY base_count.id) AS common_func                                    
ON base.id = common_func.id AND base_count.func_count = common_func.max_count   
JOIN (SELECT base.id AS id, COUNT(DISTINCT(opsyscomponents.name)) AS comp_count 
      FROM base                                                                 
      JOIN problemscomponents ON base.id = problemscomponents.problem_id        
      JOIN opsyscomponents ON problemscomponents.component_id = opsyscomponents.id
      GROUP BY base.id) AS comp                                                 
ON comp.id = base.id                                                            
JOIN problemscomponents ON base.id = problemscomponents.problem_id              
JOIN opsyscomponents ON problemscomponents.component_id = opsyscomponents.id    
LEFT JOIN (SELECT base.id AS id, STRING_AGG(opsys.name, ', ') AS name,          
                  STRING_AGG(opsysreleases.version, ', ') As version,           
                  STRING_AGG(builds.base_package_name, ', ') AS pkg_name,       
                  STRING_AGG(builds.version, ', ') AS pkg_version,              
                  STRING_AGG(builds.release, ', ') AS pkg_release               
           FROM base                                                            
           JOIN problemopsysreleases ON base.id = problemopsysreleases.problem_id
           JOIN opsysreleases ON problemopsysreleases.opsysrelease_id = opsysreleases.id
           JOIN opsys ON opsys.id = opsysreleases.opsys_id                      
           JOIN builds ON problemopsysreleases.probable_fix_build_id = builds.id
           GROUP BY base.id) AS fix                                             
ON base.id = fix.id                                                             
LEFT JOIN (SELECT base.id AS id, 1 AS count                                     
                FROM base                                                       
                JOIN reportbttaintflags ON reportbttaintflags.backtrace_id = base.rb_id
                WHERE base.report_type = 'kerneloops'                           
                GROUP BY base.id ) AS tainted                                   
ON base.id = tainted.id                                                         
LEFT JOIN reportmantis ON base.report_id = reportmantis.report_id               
LEFT JOIN mantisbugs ON reportmantis.mantisbug_id = mantisbugs.id               
LEFT JOIN reportbz ON base.report_id = reportbz.report_id                       
LEFT JOIN bzbugs ON reportbz.bzbug_id = bzbugs.id                               
 GROUP BY base.id ORDER BY count DESC
```

**Comment by xsuchy** [comment]
In `SELECT base.id AS id, COUNT(DISTINCT(opsyscomponents.name)) AS comp_count` you can add `, SUM(base.count) AS count` and then you can remove `JOIN (SELECT base.id AS id, SUM(base.count) AS count                            
      FROM base                                                                 
      GROUP BY base.id) AS total_count`

**Comment by marusak** [comment]
We need to revert raw SQL and therefore this in pointless to merge

**Pull request closed without merging**
