### PR TITLE
Ureport without packages

### PR DESCRIPTION
**Pull request by marusak**
As respsonse to:
https://github.com/abrt/libreport/pull/503
https://github.com/abrt/abrt/pull/1266
https://github.com/abrt/satyr/pull/262

### CODE REVIEW

**Comment by jfilak** [comment]
I still don't understand why you need a new bool member to store the information you can get by checking other members.

**Comment by marusak** [comment]
Which bool member? In uReport or in database?
In uReport - to know it comes from unpackaged - so then if there are no packages not to be dismiss the uReport and to be able to save in db that it is unpackaged
In DB - To be able to inform user it comes from unpackaged - so he/she does not look for the package

Where can I get this info from - from which members?

**Comment by jfilak** [comment]
> In uReport - to know it comes from unpackaged - ...

No package information denotes unpackaged problem?

> Where can I get this info from - from which members?

component-id? or no package information available?

**Comment by marusak** [comment]
> No package information denotes unpackaged problem?
Well, there are still other packages (those parsed from DSO list). But I now realised that packages are marked as 'affected' and 'related'. I'll look at that if it would be possible to consider report without `affected` package as unpackaged (even though I am a bit sceptical about that).

> component-id? or no package information available?
How could I get it from component id?

**Comment by jfilak** [comment]
> How could I get it from component id?

Null/none/0/''/empty or a well known constant?

**Comment by marusak** [comment]
>Null/none/0/''/empty

Yeah... Component is quite essential. For example it is displayed in tables in reports and problems as well. And also report without any component is useless for users (it is not imediatelly visible where does the problem happened and if I should care). Also I belive that omitting component would cause so many problems, it is not worth it.

>  or a well known constant?

That is better idea, that would not break half of the FAF, but still be quite useless for users.

**Comment by marusak** [comment]
Replaced by #590

**Pull request closed without merging**
