### PR TITLE
Remove old hook for copr build

### PR DESCRIPTION
**Pull request by mkutlak**
Improvise. Adapt. Overcome.
Related: https://github.com/abrt/faf/pull/890

Signed-off-by: Martin Kutlak <mkutlak@redhat.com>

### CODE REVIEW

**Comment by ernestask** [comment]
Oh. What is this even used for? I’ve changed the Copr projects to use tito.

**Comment by mkutlak** [comment]
`@abrt/faf-devel` - we have a badge in REAME

**Comment by ernestask** [comment]
So what? The build status is not affected by whatever is in those files.

**Comment by ernestask** [comment]
In fact, I think this is what’s causing the failures.

**Comment by ernestask** [comment]
So we should drop this and let Copr use Tito directly as configured in Copr itself.

**Comment by mkutlak** [comment]
> So what? The build status is not affected by whatever is in those files.

What? The build status shows failing builds for

**Comment by ernestask** [comment]
Wait… Oh ffs, we have multiple Copr projects.

**Comment by mkutlak** [comment]
shoot, wrong button

**Pull request merged**
