### PR TITLE
Fixes #592 to accept archive filename with milliseconds.

### LINKED ISSUE #592: Accept archives with miliseconds
Accept archive with name
ccpp-2017-10-02-14:23:33.710433-1359.tar.gz

### PR DESCRIPTION
**Pull request by gayathrirajendar**
Hello @marusak,

Following your help in the comments, I attempted this change to fix #592 . Please review. 

Thanks

### CODE REVIEW

**Comment by trapas** [comment]
Can one of the admins verify this patch?

**Comment by mkutlak** [comment]
>     In the resulting regex ".tar.gz" means "Any character followed by 'tar' followed by any character followed by gz". Which is not what we really want. Can you please match dots literally as well?

https://docs.python.org/3/library/re.html#raw-string-notation

**Comment by marusak** [comment]
Not sure how raw notation is related to this.
However:

        import re
        >>> bool(re.match(r"\.", "h"))   
        False
        >>> bool(re.match(r".", "h"))
        True

**Comment by mkutlak** [comment]
Oh, I am wrong. Don't mind me then.

**Comment by gayathrirajendar** [comment]
Thanks for the comments and the blog link @marusak . I made the changes as per that. 
On commit messages, Please correct me if it did not meet the standards yet. I shall gladly read more and make necessary changes.

**Comment by marusak** [comment]
test this please @trapas

**Comment by marusak** [comment]
@gayathrirajendar great work! :) 
I would use `dumpdirs` instead of `webfaf` as you try to be as specific as possible, but no need to change it. Lets just check if it builds and then its ready for merge.

**Comment by marusak** [comment]
test this please

**Comment by mkutlak** [comment]
@gayathrirajendar Thank you!

**Pull request merged**
